package com.moroni.tetopabrai

import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import java.util.concurrent.TimeUnit

class MainActivity : AppCompatActivity() {

    private lateinit var tickerInput: EditText
    private lateinit var epsInput: EditText
    private lateinit var priceInput: EditText
    private lateinit var analyzeButton: Button
    private lateinit var shareButton: Button

    private lateinit var introContainer: LinearLayout
    private lateinit var resultContainer: LinearLayout

    private lateinit var resultTicker: TextView
    private lateinit var resultSector: TextView
    private lateinit var resultStatusPill: TextView
    private lateinit var resultCurrentPrice: TextView
    private lateinit var resultCeilingPrice: TextView
    private lateinit var resultThesis: TextView

    private lateinit var mathEpsValue: TextView
    private lateinit var mathMultipleValue: TextView
    private lateinit var mathFairValue: TextView
    private lateinit var mathCeilingValue: TextView

    // HTTP client
    private val httpClient = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .build()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        tickerInput = findViewById(R.id.tickerInput)
        epsInput = findViewById(R.id.epsInput)
        priceInput = findViewById(R.id.priceInput)
        analyzeButton = findViewById(R.id.analyzeButton)
        shareButton = findViewById(R.id.shareButton)

        introContainer = findViewById(R.id.introContainer)
        resultContainer = findViewById(R.id.resultContainer)

        resultTicker = findViewById(R.id.resultTicker)
        resultSector = findViewById(R.id.resultSector)
        resultStatusPill = findViewById(R.id.resultStatusPill)
        resultCurrentPrice = findViewById(R.id.resultCurrentPrice)
        resultCeilingPrice = findViewById(R.id.resultCeilingPrice)
        resultThesis = findViewById(R.id.resultThesis)

        mathEpsValue = findViewById(R.id.mathEpsValue)
        mathMultipleValue = findViewById(R.id.mathMultipleValue)
        mathFairValue = findViewById(R.id.mathFairValue)
        mathCeilingValue = findViewById(R.id.mathCeilingValue)

        analyzeButton.setOnClickListener {
            handleAnalyzeClick()
        }

        shareButton.setOnClickListener {
            handleShareClick()
        }
    }

    private fun handleShareClick() {
        // Build a clean text summary from the current view state
        val ticker = resultTicker.text
        val sector = resultSector.text
        val current = resultCurrentPrice.text
        val ceiling = resultCeilingPrice.text
        val statusPill = resultStatusPill.text
        val thesis = resultThesis.text
        val eps = mathEpsValue.text
        val multiple = mathMultipleValue.text
        val fairValue = mathFairValue.text

        val summary = """
        TETO PABRAI — $ticker analysis

        Sector: $sector
        Current: $current
        Ceiling: $ceiling ($statusPill)

        Pabrai thesis:
        $thesis

        Math:
        EPS forward $eps  $multiple = Fair value $fairValue
        Pabrai discount × 0.80 = Ceiling $ceiling

        Generated by Teto Pabrai
    """.trimIndent()

        // Build an Intent that asks Android: "Send this text somewhere"
        val shareIntent = android.content.Intent().apply {
            action = android.content.Intent.ACTION_SEND
            type = "text/plain"
            putExtra(android.content.Intent.EXTRA_TEXT, summary)
            putExtra(android.content.Intent.EXTRA_SUBJECT, "Teto Pabrai — $ticker")
        }

        // Wrap it with a chooser so the system shows the app picker
        val chooser = android.content.Intent.createChooser(shareIntent, "Share analysis")
        startActivity(chooser)
    }

    private fun handleAnalyzeClick() {
        val ticker = tickerInput.text.toString().uppercase().trim()
        val eps = epsInput.text.toString().toDoubleOrNull() ?: 0.0
        val price = priceInput.text.toString().toDoubleOrNull() ?: 0.0

        // Validate inputs
        if (ticker.isEmpty() || eps <= 0 || price <= 0) {
            Toast.makeText(this, "Please fill all fields with valid numbers", Toast.LENGTH_SHORT).show()
            return
        }

        // Disable button so user can't double-tap
        analyzeButton.isEnabled = false
        analyzeButton.text = "Analyzing..."

        // Call the API
        callGitHubModels(ticker, eps, price)
    }

    private fun renderChecklist(checklistArray: JSONArray?) {
        // Find the container and clear any previous items
        val container = findViewById<LinearLayout>(R.id.checklistContainer)
        container.removeAllViews()

        if (checklistArray == null) return

        // Loop through each item the AI returned
        for (i in 0 until checklistArray.length()) {
            val item = checklistArray.getJSONObject(i)
            val name = item.optString("name", "")
            val status = item.optString("status", "WARN").uppercase()

            // Pick the badge background and icon based on status
            val badgeBackground = when (status) {
                "PASS" -> R.drawable.bg_status_pass
                "FAIL" -> R.drawable.bg_status_fail
                else -> R.drawable.bg_status_warn
            }

            val badgeIcon = when (status) {
                "PASS" -> "✓"
                "FAIL" -> "✕"
                else -> "!"
            }

            val badgeColor = when (status) {
                "PASS" -> R.color.status_pass_fg
                "FAIL" -> R.color.status_fail_fg
                else -> R.color.status_warn_fg
            }

            // Build a horizontal row: [badge] [text]
            val row = LinearLayout(this).apply {
                orientation = LinearLayout.HORIZONTAL
                gravity = android.view.Gravity.CENTER_VERTICAL
                setBackgroundResource(R.drawable.bg_checklist_chip)
                setPadding(dpToPx(10), dpToPx(8), dpToPx(10), dpToPx(8))
                layoutParams = LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT,
                    LinearLayout.LayoutParams.WRAP_CONTENT
                ).apply {
                    bottomMargin = dpToPx(6)
                }
            }

            // The badge (small colored circle with icon)
            val badge = TextView(this).apply {
                text = badgeIcon
                setTextColor(getColor(badgeColor))
                textSize = 11f
                setTypeface(typeface, android.graphics.Typeface.BOLD)
                gravity = android.view.Gravity.CENTER
                setBackgroundResource(badgeBackground)
                layoutParams = LinearLayout.LayoutParams(dpToPx(20), dpToPx(20)).apply {
                    marginEnd = dpToPx(8)
                }
            }

            // The criterion name
            val label = TextView(this).apply {
                text = name
                setTextColor(getColor(R.color.text_secondary))
                textSize = 12f
                layoutParams = LinearLayout.LayoutParams(
                    0,
                    LinearLayout.LayoutParams.WRAP_CONTENT,
                    1f
                )
            }

            row.addView(badge)
            row.addView(label)
            container.addView(row)
        }
    }

    // Helper — convert dp to pixels for use in code
    private fun dpToPx(dp: Int): Int {
        return (dp * resources.displayMetrics.density).toInt()
    }

    private fun renderAnalysis(analysis: JSONObject, eps: Double, price: Double) {
        val ticker = tickerInput.text.toString().uppercase().trim()

        // Extract fields with safe defaults
        val sector = analysis.optString("sector", "Unknown")
        val type = analysis.optString("type", "")
        val multiple = analysis.optInt("multiple", 15)
        val thesis = analysis.optString("thesis", "No thesis available.")

        // Calculate ceiling
        val fairValue = eps * multiple
        val ceiling = fairValue * 0.80
        val percentDiff = ((ceiling - price) / ceiling * 100).toInt()
        val statusText = if (percentDiff >= 0) "$percentDiff% below" else "${-percentDiff}% above"

        // Update hero
        resultTicker.text = ticker
        resultSector.text = if (type.isNotEmpty()) "$sector · $type" else sector
        resultStatusPill.text = statusText
        resultCurrentPrice.text = "$%.2f".format(price)
        resultCeilingPrice.text = "$%.2f".format(ceiling)

        // Update thesis
        resultThesis.text = thesis

        // Update math
        mathEpsValue.text = "$%.2f".format(eps)
        mathMultipleValue.text = "× $multiple"
        mathFairValue.text = "$%.2f".format(fairValue)
        mathCeilingValue.text = "$%.2f".format(ceiling)

        // Render checklist
        renderChecklist(analysis.optJSONArray("checklist"))

        // Swap visibility
        introContainer.visibility = View.GONE
        resultContainer.visibility = View.VISIBLE
    }

    private fun extractJson(raw: String): String {
        // Find the first { and the last } — everything in between is the JSON
        val firstBrace = raw.indexOf('{')
        val lastBrace = raw.lastIndexOf('}')

        if (firstBrace == -1 || lastBrace == -1 || lastBrace < firstBrace) {
            // No JSON object found — return raw so the parser fails with a useful error
            return raw.trim()
        }

        return raw.substring(firstBrace, lastBrace + 1)
    }

    private fun callGitHubModels(ticker: String, eps: Double, price: Double) {
        // Build the prompt the AI will see
        val prompt = """
            You are a value investor following Mohnish Pabrai's framework.

            Ticker: $ticker
            Forward EPS (2 years out): $$eps
            Current price: $$price

            Tasks:
            1. Identify the company and its sector.
            2. Suggest a conservative P/E multiple appropriate to this business.
            3. Calculate Fair Value = EPS × Multiple, and Pabrai Ceiling = Fair Value × 0.80.
            4. Compare ceiling to current price (% above or below).
            5. Write a 4-sentence Pabrai thesis. Avoid unverifiable superlatives like "only" or "first" unless certain.
            6. Score the 8-criterion checklist as PASS, WARN, or FAIL based on what you know.

            Return ONLY valid JSON with this exact structure, no markdown, no commentary:
            {
              "company": "Company Name",
              "sector": "Sector",
              "type": "Monopoly|Bank|Cyclical|Regular|Emerging Market",
              "multiple": 20,
              "thesis": "Four sentence thesis here.",
              "checklist": [
                {"name": "ROIC > 15%", "status": "PASS"},
                {"name": "FCF growth", "status": "PASS"},
                {"name": "Debt < 3x", "status": "PASS"},
                {"name": "Remuneration", "status": "PASS"},
                {"name": "Payout", "status": "PASS"},
                {"name": "PEG < 2", "status": "PASS"},
                {"name": "Price OK", "status": "PASS"},
                {"name": "Moat 10y", "status": "PASS"}
              ]
            }
        """.trimIndent()

        // Build the request body matching GitHub Models API format
        val requestJson = JSONObject().apply {
            put("model", "gpt-4o")
            put("messages", JSONArray().apply {
                put(JSONObject().apply {
                    put("role", "user")
                    put("content", prompt)
                })
            })
            put("temperature", 0.3)
        }

        val requestBody = requestJson.toString().toRequestBody("application/json".toMediaType())

        val request = Request.Builder()
            .url("https://models.inference.ai.azure.com/chat/completions")
            .header("Authorization", "Bearer ${BuildConfig.GITHUB_MODELS_TOKEN}")
            .header("Content-Type", "application/json")
            .post(requestBody)
            .build()

        // Make the call asynchronously (HTTP must NOT run on the main thread)
        httpClient.newCall(request).enqueue(object : okhttp3.Callback {
            override fun onFailure(call: okhttp3.Call, e: IOException) {
                // Network failure
                Log.e("TetoPabrai", "Network error", e)
                runOnUiThread {
                    Toast.makeText(this@MainActivity, "Network error: ${e.message}", Toast.LENGTH_LONG).show()
                    resetButton()
                }
            }

            override fun onResponse(call: okhttp3.Call, response: okhttp3.Response) {
                response.use {
                    val body = it.body?.string() ?: ""
                    Log.d("TetoPabrai", "API response: $body")

                    if (!it.isSuccessful) {
                        runOnUiThread {
                            Toast.makeText(this@MainActivity, "API error: ${it.code}", Toast.LENGTH_LONG).show()
                            resetButton()
                        }
                        return
                    }

                    // Parse the response
                    try {
                        val responseJson = JSONObject(body)
                        val rawContent = responseJson
                            .getJSONArray("choices")
                            .getJSONObject(0)
                            .getJSONObject("message")
                            .getString("content")

                        Log.d("TetoPabrai", "Raw AI content: $rawContent")

                        // Find the actual JSON object inside the response
                        val aiContent = extractJson(rawContent)

                        Log.d("TetoPabrai", "Cleaned AI content: $aiContent")

                        val analysis = JSONObject(aiContent)

                        runOnUiThread {
                            renderAnalysis(analysis, eps, price)
                            resetButton()
                        }
                    } catch (e: Exception) {
                        Log.e("TetoPabrai", "Parse error", e)
                        runOnUiThread {
                            Toast.makeText(this@MainActivity, "Couldn't parse AI response. Try again.", Toast.LENGTH_LONG).show()
                            resetButton()
                        }
                    }
                }
            }
        })
    }

    private fun resetButton() {
        analyzeButton.isEnabled = true
        analyzeButton.text = "Analyze"
    }
}